# Generated by Django 5.1.3 on 2024-11-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewelcomebutton',
            name='css_class',
            field=models.TextField(help_text='Tugmaga qo‘llanadigan CSS class nomini kiriting', verbose_name='CSS Class'),
        ),
    ]
