# Generated by Django 5.1.3 on 2024-11-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_homewelcomebutton_css_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRightButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tugmada ko‘rsatiladigan sarlavhani kiriting', max_length=255, verbose_name='Tugma Sarlavhasi')),
                ('link', models.CharField(help_text='Tugma bosilganda yo‘naltiriladigan URL havolani kiriting', verbose_name='Havola')),
                ('css_class', models.TextField(help_text='Tugmaga qo‘llanadigan CSS class nomini kiriting', verbose_name='CSS Class')),
            ],
            options={
                'verbose_name': "3. Fan mashg'ulotlari o'ng tugmasi",
                'verbose_name_plural': "3. Fan mashg'ulotlari o'ng tugmalari",
            },
        ),
    ]
