# Generated by Django 5.1.3 on 2024-11-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_courserightbutton'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserightbutton',
            options={'verbose_name': "2. Fan mashg'ulotlari o'ng tugmasi", 'verbose_name_plural': "2. Fan mashg'ulotlari o'ng tugmasi"},
        ),
    ]
