# Generated by Django 5.1.3 on 2024-11-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_alter_courserightbutton_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserightbutton',
            options={'verbose_name': "3. Fan mashg'ulotlari o'ng tugmasi", 'verbose_name_plural': "3. Fan mashg'ulotlari o'ng tugmasi"},
        ),
        migrations.AlterModelOptions(
            name='homewelcomebutton',
            options={'verbose_name': '2. Hush kelibsiz tugmalar', 'verbose_name_plural': '2. Hush kelibsiz tugmalar'},
        ),
    ]
