# Generated by Django 5.1.3 on 2024-11-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_alter_courserightbutton_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=455, verbose_name='Ism familiya')),
                ('phone', models.CharField(max_length=455, verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi?")),
            ],
            options={
                'verbose_name': '4. Xabar',
                'verbose_name_plural': '4. Xabarlar',
            },
        ),
    ]
