# Generated by Django 5.1.3 on 2024-11-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_aboutauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('option_a', models.CharField(max_length=255, verbose_name='Javob A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Javob B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Javob C')),
                ('option_d', models.CharField(max_length=255, verbose_name='Javob D')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='To‘g‘ri javob')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': '9. Savol',
                'verbose_name_plural': '9. Savollar',
            },
        ),
    ]
