# Generated by Django 5.1.3 on 2024-11-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kategoriyaning nomini kiriting', max_length=255, verbose_name='Kategoriya nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kategoriya yaratilgan vaqt', verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kategoriya yangilangan vaqt', verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Yangilik rasmini kiriting', upload_to='news-images', verbose_name='Yangilik rasmi')),
                ('title', models.CharField(help_text='Yangilikning sarlavhasini kiriting', max_length=255, verbose_name='Yangilik sarlavhasi')),
                ('content', models.TextField(help_text="Yangilikning to'liq matnini kiriting", verbose_name='Yangilik matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kategoriya yaratilgan vaqt', verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kategoriya yangilangan vaqt', verbose_name='Yangilangan sana')),
                ('category', models.ForeignKey(help_text="Yangilik tegishli bo'lgan kategoriyani tanlang", on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news_app.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
