# Generated by Django 5.1.3 on 2024-11-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kursning qisqa nomi yoki sarlavhasi.', max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(help_text='Kursning batafsil tavsifi.', verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, help_text='Kurs uchun rasm (ixtiyoriy).', null=True, upload_to='courses/', verbose_name='Rasm')),
                ('link', models.TextField(help_text="Kurs haqida qo'shimcha ma'lumot sahifasi yoki havola.", verbose_name='Havola')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kursning yaratilgan sanasi va vaqti.', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kursning oxirgi yangilangan sanasi va vaqti.', verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': "Mashg'ulot",
                'verbose_name_plural': "Mashg'ulotlar",
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kurs toifasining qisqa sarlavhasi.', max_length=255, verbose_name='Sarlavha')),
                ('cap_title', models.CharField(help_text='Toifa uchun asosiy bosh sarlavha.', max_length=255, verbose_name='Bosh sarlavha')),
                ('description', models.TextField(help_text='Kurs toifasining batafsil tavsifi.', verbose_name='Tavsif')),
                ('link', models.CharField(help_text="Toifaga havola yoki qo'shimcha ma'lumot sahifasi.", verbose_name='Havola')),
                ('image', models.ImageField(help_text='Kurs toifasi uchun rasm.', upload_to='course_categories/', verbose_name='Rasm')),
                ('file_image', models.ImageField(help_text='Fayl uchun rasm.', upload_to='course_images/', verbose_name='Fayl uchun rasm')),
            ],
            options={
                'verbose_name': 'Kurs toifasi',
                'verbose_name_plural': 'Kurs toifalari',
            },
        ),
    ]
