# Generated by Django 5.1.3 on 2024-11-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': "2. Mashg'ulot", 'verbose_name_plural': "2. Mashg'ulotlar"},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': '1. Kategoriya', 'verbose_name_plural': '1. Kategoriyalar'},
        ),
    ]
