# Generated by Django 5.1.3 on 2024-11-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='Sayt nomi', max_length=255, verbose_name='Sayt nomi')),
                ('site_description', models.TextField(help_text='Saytning qisqacha tavsifi', verbose_name='Sayt tavsifi')),
                ('site_keywords', models.CharField(help_text="Sayt uchun kalit so'zlar, vergul bilan ajratilgan", max_length=255, verbose_name="Kalit so'zlar")),
                ('site_author', models.CharField(blank=True, help_text='Sayt muallifi', max_length=255, null=True, verbose_name='Sayt muallifi')),
                ('site_logo', models.ImageField(blank=True, help_text='Sayt logotipi', null=True, upload_to='seo_settings/logos/', verbose_name='Sayt logotipi')),
                ('site_favicon', models.ImageField(blank=True, help_text='Saytning favicon rasm fayli', null=True, upload_to='seo_settings/favicon/', verbose_name='Sayt faviconi')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Sozlama yaratish vaqti', verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Sozlamalar oxirgi marta yangilangan vaqt', verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'SEO Sozlama',
                'verbose_name_plural': 'SEO Sozlamalari',
            },
        ),
    ]
