# Generated by Django 5.1.3 on 2024-11-11 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Navbar nomi')),
                ('link', models.CharField(verbose_name='Havola')),
                ('is_submenu', models.BooleanField(default=False, verbose_name='Ichma ich menyumi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yangilangan vaqti')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu_items', to='settings_app.navbar', verbose_name='Parentni belgilash')),
            ],
            options={
                'verbose_name': 'Navbar',
                'verbose_name_plural': 'Navbarlar',
            },
        ),
    ]
