# Generated by Django 5.1.3 on 2024-11-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='site_css',
            field=models.TextField(blank=True, help_text='Sayt CSS sozlamalari', null=True, verbose_name='Sayt CSS sozlamalari'),
        ),
    ]
